AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
