name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0' ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.2.19
          bundler-cache: true

      - name: Set up Bundler
        run: |
          export BUNDLE_PATH=$PWD/vendor/bundle

          gem update --system

          bundle config set path $PWD/$BUNDLE_PATH
          bundle install --jobs=4 --retry=3
          bundle update
      - name: RSpec
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: 2.2.19
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
